<Project>
  <PropertyGroup>
    <!--Empty RootNamespace does not work in Directory.Build.props, so put it in this file as a workaround-->
    <RootNamespace></RootNamespace>
  </PropertyGroup>
  <ItemGroup Condition="$([MSBuild]::VersionLessThan($(TargetFrameworkVersion), 8.0))">
    <PackageReference Include="PolySharp" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>$(AssemblyName).Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>
</Project>