<Project>
  <Import Project="..\build\Package.props" />
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <LangVersion>latest</LangVersion>
    <NoWarn>$(NoWarn);CS1591;CS8500;NU1900;NU5104</NoWarn>
    <Nullable>enable</Nullable>
    <SuppressTfmSupportBuildWarnings>true</SuppressTfmSupportBuildWarnings>
    <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0;net472</TargetFrameworks>
    <WarningsAsErrors>CS8785</WarningsAsErrors>
  </PropertyGroup>
  <PropertyGroup>
    <IsWindows>$([MSBuild]::IsOSPlatform('Windows'))</IsWindows>
    <TargetFrameworkVersion>$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)', 2))</TargetFrameworkVersion>
  </PropertyGroup>
</Project>